config {
    type: "table",
    columns: {
        first_name: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        last_name: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        previous_name: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        date_of_birth: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        email_address: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        trn: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        address_line_1: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        address_line_2: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        town_or_city: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        postcode: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        country: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        phone_number: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        ni_number: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        work_location_known: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        work_organisation_name: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        work_address_line_1: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        work_address_line_2: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        work_town_or_city: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        work_postcode: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        organisation_address_known: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        organisation_name: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        organisation_address_line_1: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        organisation_address_line_2: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        organisation_town_or_city: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        organisation_postcode: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        allegation_details: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        allegation_consideration_details: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        previous_misconduct_details: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        },
        duties_details: {
            bigqueryPolicyTags: ["projects/refer-serious-misconduct/locations/europe-west2/taxonomies/222536751192641232/policyTags/1060373956414181161"]
        }
    }
}

SELECT
  * EXCEPT(id,
    updated_at,
    created_at,
    last_streamed_event_occurred_at,
    last_streamed_event_type),
  tableB.id AS referral_id,
  tableB.created_at AS referral_created_at,
  tableA.created_at AS eligibility_created_at,
FROM
  ${ref("eligibility_checks_latest_prod")} AS tableA
LEFT JOIN
  ${ref("referrals_latest_prod")} AS tableB
ON
  tableA.id = tableB.eligibility_check_id
